/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __MYAPP_GENERATED_H__
#define __MYAPP_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


G_END_DECLS

#endif /* __MYAPP_GENERATED_H__ */
